.. _changelog-r104:

************************
Release August 16th 2022
************************
We are back after the summer. 

As always the API and backend has been rolled out entirely, and the frontend/UI will be rolled out over the next couple of days, some UI instances have already been deployed.

We are slowly migrating to a new deployment type for the administrative merchant UI, which should lead to simplified access and increased performance for most tenants.
Each tenant will be contacted directly to arrange for the details on when to make the switch.

API and Backend
===============
The following new features and improvements are now available in the API and the backend.

Merchant Client
===============
The following new features and improvements are now available in the merchant client.

* Support for ADB2C as an end-user backend. *Preview*
* UI changes related to Enterprise Plan to make it more streamlined and simpler to use.
* Changed the sub-menu tab order for the Subscriber View.
* Removed the possibility to update a temporary change AFTER it has been started.
* Fixed an issue where entering a future date would use UTC midnight as the starting time instead of local midnight.
* Reminder settings now displays the delay as integers instead of decimals.
* Multiple visual adjustments for subscriberview and for the plan change view.
* Temporary changes are now out of preview.


Self-Service and Salesposter
============================
The following new features and improvements are now available in the self-service client

* Support for ADB2C as an end-user backend *Preview*